workflows:
  android-session-installer:
    name: Rto Installer Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - sdk_config
      vars:
        PACKAGE_NAME: "com.example.rtoechallan"
      node: latest
      java: 17
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Build Android APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - YOUR_EMAIL@gmail.com # Yahan apni email dalo jahan APK chahiye

